import { ChapterDefinition } from "../engine/narrative/types";

export const CHAPTERS: ChapterDefinition[] = [
  {
    id: "chapter-1",
    title: "New Beginnings",
    objectives: [
      {
        id: "explore_home",
        description: "Explore your personal files",
        check: { source: "storyFlag", key: "read_resume" },
        optional: true,
      },
      {
        id: "fix_backup",
        description: "Fix the backup script",
        check: { source: "storyFlag", key: "fixed_backup_script" },
        hidden: true,
        visibleWhen: { source: "storyFlag", key: "read_cron_backup" },
        optional: true,
      },
      {
        id: "run_auto_apply",
        description: "Run the job application script",
        check: { source: "storyFlag", key: "ran_auto_apply" },
        optional: true,
      },
      {
        id: "check_email",
        description: "Check your email",
        check: { source: "storyFlag", key: "read_nexacorp_offer" },
      },
      {
        id: "accept_offer",
        description: "Accept the job offer",
        check: { source: "completedObjective", key: "accepted_nexacorp" },
        failCheck: { source: "completedObjective", key: "rejected_nexacorp_final" },
      },
    ],
  },
  {
    id: "chapter-2",
    title: "First Day",
    objectives: [
      {
        id: "read_welcome_email",
        description: "Read Edward's welcome email",
        check: { source: "storyFlag", key: "piper_unlocked" },
      },
      {
        id: "read_onboarding",
        description: "Read the onboarding docs",
        check: { source: "storyFlag", key: "read_onboarding" },
      },
      {
        id: "meet_the_team",
        description: "Read the team directory",
        check: { source: "storyFlag", key: "read_team_info" },
      },
      {
        id: "review_handoff",
        description: "Review Jin Chen's handoff notes",
        check: { source: "storyFlag", key: "read_handoff_notes" },
      },
      {
        id: "run_dbt",
        description: "Run the data pipeline",
        check: { source: "storyFlag", key: "ran_dbt" },
      },
      {
        id: "oscar_search_logs",
        description: "Search the system logs for errors",
        check: { source: "storyFlag", key: "oscar_searched_logs" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "search_tools_accepted" },
      },
      {
        id: "oscar_check_backups",
        description: "Check the backup logs",
        check: { source: "storyFlag", key: "oscar_checked_backups" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "search_tools_accepted" },
      },
      {
        id: "oscar_diff_logs",
        description: "Diff the active and backup logs",
        check: { source: "storyFlag", key: "oscar_diffed_logs" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "search_tools_accepted" },
      },
      {
        id: "auri_use_head",
        description: "Check the header row of the pipeline runs",
        check: { source: "storyFlag", key: "auri_used_head" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
      },
      {
        id: "auri_use_tail",
        description: "Check the last few entries",
        check: { source: "storyFlag", key: "auri_used_tail" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
      },
      {
        id: "auri_use_wc",
        description: "Count the total lines",
        check: { source: "storyFlag", key: "auri_used_wc" },
        hidden: true,
        optional: true,
        visibleWhen: { source: "completedObjective", key: "inspection_tools_accepted" },
      },
      {
        id: "explore_jchen",
        description: "Investigate Jin Chen's files",
        check: { source: "storyFlag", key: "found_backup_files" },
        hidden: true,
        optional: true,
      },
      {
        id: "discover_tampering",
        description: "Discover the log discrepancies",
        check: { source: "storyFlag", key: "discovered_log_tampering" },
        hidden: true,
        prerequisite: "explore_jchen",
        optional: true,
      },
      {
        id: "find_directives",
        description: "Find the operational directives",
        check: { source: "storyFlag", key: "found_chip_directives" },
        hidden: true,
        prerequisite: "explore_jchen",
        optional: true,
      },
      {
        id: "find_filtering",
        description: "Discover the data filtering",
        check: { source: "storyFlag", key: "found_data_filtering" },
        hidden: true,
        prerequisite: "run_dbt",
        optional: true,
      },
    ],
  },
];
