export const HOME_PATHS = {
  resume: (u: string) => `/home/${u}/Downloads/resume_final_v3.pdf`,
  downloadsDir: (u: string) => `/home/${u}/Downloads`,
  zoomDeb: (u: string) => `/home/${u}/Downloads/zoom_amd64.deb`,
  pipDeb: (u: string) => `/home/${u}/Downloads/python3-pip_24.0+dfsg-1_all.deb`,
  jobJd: (u: string) => `/home/${u}/Downloads/NexaCorp_AI_Engineer_JD.pdf`,
  projectsDir: (u: string) => `/home/${u}/Projects`,
  syntheticaDir: (u: string) => `/home/${u}/.cache/synthetica`,
  syntheticaHeartbeat: (u: string) => `/home/${u}/.cache/synthetica/.heartbeat`,
  synthEvalPipe: () => `/tmp/.synth_eval_pipe`,
  backupLog: (u: string) => `/home/${u}/backup.log`,
  backupsScripts: (u: string) => `/home/${u}/backups/scripts/backup.sh`,
  backupsDir: (u: string) => `/home/${u}/backups`,
  dbtProject: (u: string) => `/home/${u}/nexacorp-analytics`,
  dbtDimEmployees: (u: string) => `/home/${u}/nexacorp-analytics/models/marts/dim_employees.sql`,
  dbtFctTickets: (u: string) => `/home/${u}/nexacorp-analytics/models/marts/fct_support_tickets.sql`,
  dbtChipTicketSuppression: (u: string) => `/home/${u}/nexacorp-analytics/models/_chip_internal/chip_ticket_suppression.sql`,
  dbtChipLogFilter: (u: string) => `/home/${u}/nexacorp-analytics/models/_chip_internal/chip_log_filter.sql`,
  dbtChipDataCleanup: (u: string) => `/home/${u}/nexacorp-analytics/models/_chip_internal/chip_data_cleanup.sql`,
  jobSearchLog: (u: string) => `/home/${u}/job_search_log.txt`,
  myCommandsTxt: (u: string) => `/home/${u}/my_commands.txt`,
} as const;

export const NEXACORP_PATHS = {
  accessLog: "/var/log/access.log",
  systemLog: "/var/log/system.log",
  systemLogBak: "/var/log/system.log.bak",
  authLogBak: "/var/log/auth.log.bak",
  chipDirectives: "/opt/chip/.internal/directives.txt",
  chipCleanup: "/opt/chip/.internal/cleanup.sh",
  onboarding: "/srv/engineering/onboarding.md",
  teamInfo: "/srv/engineering/team-info.md",
  chenHandoff: "/srv/engineering/chen-handoff",
  chenHandoffTodo: "/srv/engineering/chen-handoff/todo.txt",
  handoffNotes: "/srv/engineering/chen-handoff/notes.txt",
  ticketExport: "/srv/operations/ticket_export.csv",
  boardMinutes: "/srv/leadership/board_minutes_feb.md",
  headcountPlan: "/srv/leadership/headcount_plan.csv",
} as const;
