export const HELP_TEXTS: Record<string, string> = {
  pwd: [
    "Usage: pwd",
    "",
    "Print the full filename of the current working directory.",
  ].join("\n"),

  cd: [
    "Usage: cd [DIRECTORY]",
    "",
    "Change the current directory to DIRECTORY.",
    "If no DIRECTORY is given, change to the home directory (~).",
    "",
    "  cd ..         Go up one level",
    "  cd ~          Go to home directory",
    "  cd /path      Go to absolute path",
  ].join("\n"),

  ls: [
    "Usage: ls [OPTION]... [FILE]...",
    "",
    "List directory contents.",
    "",
    "  -a, --all              do not ignore entries starting with .",
    "  -A, --almost-all       like -a but do not list . and ..",
    "  -C                     list entries by columns",
    "  -F                     append indicator (one of */) to entries",
    "  -l                     use a long listing format",
    "  -h, --human-readable   print sizes in human readable format",
  ].join("\n"),

  cat: [
    "Usage: cat [-n] [FILE]...",
    "",
    "Concatenate FILE(s) and print to standard output.",
    "With no FILE, or when FILE is missing, display an error.",
    "",
    "  -n   number all output lines",
  ].join("\n"),

  clear: [
    "Usage: clear",
    "",
    "Clear the terminal screen.",
  ].join("\n"),

  nano: [
    "Usage: nano [FILE]",
    "",
    "Open FILE in the nano text editor.",
    "If FILE does not exist, create a new file.",
    "",
    "  Ctrl+S   Save the file",
    "  Ctrl+X   Exit the editor",
  ].join("\n"),

  vim: [
    "Usage: vim [FILE]",
    "",
    "Open FILE in the vim modal text editor (alias: vi).",
    "If FILE does not exist, create a new file.",
    "",
    "  i / a / o        Enter insert mode (Esc returns to normal mode)",
    "  h j k l          Move the cursor; w/b/e by word, 0/^/$ within the line",
    "  gg / G / f{c}    First/last line; jump to next {c} in the line; :5 to line 5",
    "  x / r{c}         Delete character / replace character",
    "  dd / yy / p      Delete / yank the line, paste; dw, d$, 3dd etc.",
    "  v / V            Visual (character / line) selection",
    "  u / Ctrl+R       Undo / redo",
    "  /text            Search (n/N for next/previous match)",
    "  :w  :q  :wq  :q! Save, quit, save-and-quit, quit without saving",
  ].join("\n"),

  python: [
    "Usage: python [FILE] [-c CODE]",
    "",
    "Run the Python interpreter.",
    "",
    "  python              Start interactive REPL",
    "  python script.py    Run a Python script",
    "  python -c 'code'    Execute Python code inline",
  ].join("\n"),

  snow: [
    "Usage: snow COMMAND [OPTIONS]",
    "",
    "Snowflake CLI: query the NexaCorp data warehouse.",
    "",
    "Commands:",
    "  sql    Execute SQL queries",
    "",
    "  snow sql             Start interactive SQL REPL",
    "  snow sql -q 'SQL'    Execute a single query inline",
  ].join("\n"),

  dbt: [
    "Usage: dbt COMMAND [OPTIONS]",
    "",
    "dbt (data build tool): transform data in the warehouse.",
    "",
    "  dbt run [-s <model>]      Run all models (-s/--select: just one model)",
    "  dbt test                  Run data tests",
    "  dbt build [-s <model>]    Run models then tests",
    "  dbt ls [--resource-type <type>]  List resources (alias: dbt list)",
    "  dbt debug                 Show connection info",
    "  dbt compile [-s <model>]  Show compiled SQL",
    "  dbt show [-s <model>]     Preview model output",
    "  dbt --version             Show dbt version",
  ].join("\n"),

  grep: [
    "Usage: grep [OPTIONS] PATTERN [FILE...]",
    "",
    "Search for PATTERN in each FILE.",
    "",
    "  -r, -R        search recursively",
    "  -i            ignore case distinctions",
    "  -n            print line numbers",
    "  -l            print only filenames with matches",
    "  -c            print only a count of matching lines",
    "  -v            invert match (select non-matching lines)",
  ].join("\n"),

  find: [
    "Usage: find [PATH] [EXPRESSIONS]",
    "",
    "Search for files in a directory hierarchy.",
    "",
    "  -name PATTERN   match filename (supports * and ? globs)",
    "  -type f|d       match file type (f=file, d=directory)",
  ].join("\n"),

  head: [
    "Usage: head [-n LINES] [FILE...]",
    "",
    "Display the first 10 lines of each FILE.",
    "",
    "  -n NUM   output the first NUM lines",
    "  -NUM     same as -n NUM (e.g. head -5 file)",
  ].join("\n"),

  tail: [
    "Usage: tail [-n LINES] [FILE...]",
    "",
    "Display the last 10 lines of each FILE.",
    "",
    "  -n NUM        output the last NUM lines",
    "  -NUM          same as -n NUM (e.g. tail -5 file)",
    "  -f, --follow  follow appended data (not supported in this terminal)",
  ].join("\n"),

  less: [
    "Usage: less [-N] [FILE]",
    "",
    "View file contents with paging. With no FILE, read from standard input.",
    "",
    "  -N   number each line",
    "",
    "  q  Ctrl+C       Quit",
    "  j  Down  Enter  Forward one line",
    "  k  Up           Backward one line",
    "  Space  f  PgDn  Forward one page",
    "  b  PgUp         Backward one page",
    "  g               Go to first line",
    "  G               Go to last line",
    "  /pattern        Search forward",
    "  ?pattern        Search backward",
    "  n / N           Next / previous match",
    "  Ctrl+L          Redraw screen",
    "  h               In-pager help",
  ].join("\n"),

  diff: [
    "Usage: diff [OPTION]... FILE1 FILE2",
    "",
    "Compare two files line by line.",
    "Lines only in FILE1 are shown with - (red).",
    "Lines only in FILE2 are shown with + (green).",
    "",
    "  -u   output in unified format with @@ hunk headers",
    "  -r   recursively compare any subdirectories found",
  ].join("\n"),

  wc: [
    "Usage: wc [OPTION]... [FILE...]",
    "",
    "Print line, word, and byte counts for each FILE.",
    "",
    "  -l                     print the line count",
    "  -w                     print the word count",
    "  -c                     print the character count",
    "  -h, --human-readable   print byte counts in human readable format",
  ].join("\n"),

  echo: [
    "Usage: echo [-n] [TEXT...]",
    "",
    "Print TEXT to standard output.",
    "",
    "  -n   do not output trailing newline",
  ].join("\n"),

  chmod: [
    "Usage: chmod [-R] MODE FILE...",
    "",
    "Change file permissions. MODE may be octal or symbolic.",
    "",
    "  -R, --recursive   change permissions recursively",
    "",
    "Octal mode: three digits for owner, group, others.",
    "  7 = rwx, 6 = rw-, 5 = r-x, 4 = r--, 0 = ---",
    "",
    "Symbolic mode: [ugoa][+-=][rwx][,...]",
    "  u=owner, g=group, o=others, a=all (default)",
    "  + add, - remove, = set exactly",
    "",
    "Examples:",
    "  chmod 755 dir/       owner=rwx, group=r-x, others=r-x",
    "  chmod +x script.sh   add execute for everyone",
    "  chmod u+w,go-r f     give owner write, strip group/other read",
    "  chmod -R 750 src/    apply 750 recursively",
  ].join("\n"),

  mkdir: [
    "Usage: mkdir [-p] DIRECTORY...",
    "",
    "Create directories.",
    "",
    "  -p   create parent directories as needed",
  ].join("\n"),

  rm: [
    "Usage: rm [OPTION]... FILE...",
    "",
    "Remove files or directories.",
    "",
    "  -r, -R   remove directories and their contents recursively",
    "  -f       ignore nonexistent files, never prompt",
  ].join("\n"),

  mv: [
    "Usage: mv SOURCE DEST",
    "",
    "Move (rename) files or directories.",
    "If DEST is an existing directory, SOURCE is moved inside it.",
    "Directories move recursively; no flag required.",
  ].join("\n"),

  cp: [
    "Usage: cp [OPTION]... SOURCE DEST",
    "",
    "Copy files and directories.",
    "",
    "  -r, -R   copy directories recursively",
  ].join("\n"),

  touch: [
    "Usage: touch FILE...",
    "",
    "Create empty files or update timestamps.",
  ].join("\n"),

  history: [
    "Usage: history",
    "",
    "Display command history.",
  ].join("\n"),

  whoami: [
    "Usage: whoami",
    "",
    "Print the current username.",
  ].join("\n"),

  file: [
    "Usage: file FILE...",
    "",
    "Determine file type.",
  ].join("\n"),

  pdftotext: [
    "Usage: pdftotext FILE",
    "",
    "Extract text content from a PDF file.",
  ].join("\n"),

  tree: [
    "Usage: tree [OPTION]... [DIRECTORY]",
    "",
    "List contents of directories in a tree-like format.",
    "",
    "  -a, --all   all files are listed",
    "  -L NUM      descend only NUM directory levels deep",
  ].join("\n"),

  sort: [
    "Usage: sort [OPTION]... [FILE]",
    "",
    "Sort lines of text.",
    "",
    "  -r   reverse the result of comparisons",
    "  -n   compare according to string numerical value",
    "  -u   output only the first of an equal run",
  ].join("\n"),

  uniq: [
    "Usage: uniq [OPTION]... [FILE]",
    "",
    "Filter adjacent duplicate lines.",
    "",
    "  -c   prefix lines by the number of occurrences",
    "  -d   only print duplicate lines",
    "  -i   ignore differences in case when comparing",
  ].join("\n"),

  date: [
    "Usage: date",
    "",
    "Display the current date and time.",
  ].join("\n"),

  which: [
    "Usage: which COMMAND",
    "",
    "Show the full path of a command.",
  ].join("\n"),

  command: [
    "Usage: command -v COMMAND",
    "",
    "Print the path of COMMAND, or nothing if not found.",
    "POSIX-portable alternative to 'which'.",
  ].join("\n"),

  type: [
    "Usage: type [-a] COMMAND...",
    "",
    "Describe how COMMAND would be interpreted (path, alias, builtin).",
    "",
    "  -a   show all locations where COMMAND can be found",
  ].join("\n"),

  man: [
    "Usage: man COMMAND",
    "",
    "Display manual page for COMMAND.",
  ].join("\n"),

  shortcuts: [
    "Usage: shortcuts",
    "",
    "Show keyboard shortcuts for the command line, scrollback, and terminal tabs.",
  ].join("\n"),

  df: [
    "Usage: df [-h]",
    "",
    "Report filesystem disk space usage.",
    "",
    "  -h, --human-readable   print sizes in human readable format",
  ].join("\n"),

  lsblk: [
    "Usage: lsblk [OPTION]...",
    "",
    "List information about all available block devices.",
    "",
    "  -f   show filesystem type and mountpoints",
  ].join("\n"),

  mount: [
    "Usage: mount [DEVICE DIR]",
    "",
    "Mount a filesystem at DIR. With no arguments, list active mounts.",
    "DIR must be an existing empty directory.",
    "",
    "Examples:",
    "  lsblk                      list block devices to find the partition",
    "  mount /dev/sdb1 /mnt/usb   mount the USB partition at /mnt/usb",
    "  mount                      list what is currently mounted",
  ].join("\n"),

  umount: [
    "Usage: umount {DIR | DEVICE}",
    "",
    "Unmount a filesystem. The argument may be the mountpoint or the device.",
  ].join("\n"),

  git: [
    "Usage: git <command> [<args>]",
    "",
    "The distributed version control system.",
    "",
    "  git init                        Create an empty repository",
    "  git clone [-b <branch>] <url>   Clone a remote repo (-b: check out <branch>)",
    "  git add <file|.|-A>             Stage changes for commit (-A: everything)",
    "  git status [-s]                 Show the working tree status (-s: short format)",
    "  git commit -m 'msg'             Record staged changes to the repository",
    "      -a: also stage modified tracked files    --amend: replace the last commit",
    "  git log [-n <count>] [<rev>] [-- <path>]   Show commit history",
    "      --oneline: one line each    --graph: with branch graph",
    "      <rev>: a branch, HEAD, or a commit — with ~N / ^ / ^2 steps (e.g. HEAD~2)",
    "  git branch [<name>]             List branches, or create branch <name>",
    "      -a: include remote branches    -d/-D: delete a branch (-D even if unmerged)",
    "  git switch [-c] <branch>        Switch branches (-c: create it first)",
    "      -d/--detach <commit>: detach HEAD onto a commit instead of a branch",
    "  git checkout [-b] <branch>      Switch or create branches (legacy; -b: create)",
    "  git checkout <commit>           Detach HEAD onto a commit (e.g. a sha, HEAD~1)",
    "  git checkout -- <file>          Discard working-tree changes (legacy; see restore)",
    "  git diff [--staged] [<rev>[..<rev>]] [-- <path>]   Show changes",
    "      --staged: staged instead of unstaged    <rev>: compare against a commit",
    "  git restore [--staged] <file>   Discard working-tree changes (--staged: unstage)",
    "  git merge [--ff-only] <rev>     Join another history into this branch",
    "      fast-forwards when possible, else makes a merge commit",
    "      --ff-only: fail instead of making a merge commit",
    "  git merge --continue|--abort    Conclude or cancel a conflicted merge",
    "  git rebase <branch>             Reapply your commits on top of another branch",
    "  git rebase --continue|--abort   Resume or cancel an in-progress rebase",
    "  git reset [<paths>]             Unstage changes",
    "  git reset [--soft|--mixed|--hard] <commit>   Move HEAD to a commit (e.g. HEAD~1)",
    "      --soft: keep changes staged    --mixed: keep unstaged    --hard: discard them",
    "  git push [-u] [-f] [origin <branch>]   Update remote refs",
    "      -u: set upstream for the branch    -f: force (overwrite remote history)",
    "  git fetch                       Download remote refs (already up to date here)",
    "  git pull [--ff-only|--rebase]   Fetch and merge from remote",
    "      --ff-only: fail rather than merge    --rebase: replay your commits on top",
    "  git rm [-r] <file>              Remove files from tracking (-r: recurse into dirs)",
    "  git stash [push] [-u]           Set changes aside (-u: include untracked files)",
    "  git stash pop                   Re-apply the most recent stash",
    "  git stash list                  List stashes",
  ].join("\n"),

  true: [
    "Usage: true",
    "",
    "Do nothing, successfully (exit code 0).",
  ].join("\n"),

  false: [
    "Usage: false",
    "",
    "Do nothing, unsuccessfully (exit code 1).",
  ].join("\n"),

  bash: [
    "Usage: bash [SCRIPT] [-c COMMAND]",
    "",
    "Execute shell scripts or commands.",
    "",
    "  bash script.sh       Run a shell script",
    "  bash -c 'command'    Execute a command string",
    "  ./script.sh          Run an executable script directly",
  ].join("\n"),

  source: [
    "Usage: source FILENAME",
    "",
    "Execute commands from a file in the current shell.",
    "",
    "  source ~/.zshrc      Reload shell configuration",
    "  . ~/.zshrc           Shorthand (POSIX dot command)",
  ].join("\n"),

  help: [
    "Usage: help",
    "",
    "List available commands.",
    "Use man <command> for detailed usage.",
  ].join("\n"),

  sudo: [
    "Usage: sudo COMMAND [ARG ...]",
    "",
    "Run a command with elevated privileges.",
    "Required for system operations like installing packages.",
  ].join("\n"),

  tmux: [
    "Usage: tmux [command [flags]]",
    "",
    "Terminal multiplexer. With no command, starts a new session.",
    "",
    "  new [-s name]           Start a new session (default name: lowest unused number)",
    "  ls                      List sessions",
    "  attach [-t name]        Attach to a session (default: most recently detached)",
    "  detach                  Detach from the current session (also <prefix> d)",
    "  rename-session [-t name] new-name",
    "                          Rename a session (default target: the current one)",
    "  kill-session [-t name]  Destroy a session",
    "  kill-server             Destroy all sessions and stop the server",
    "",
    "Windows (-t targets a window by name or 1-based index; default: current):",
    "",
    "  new-window              Create a window (neww)",
    "  rename-window [-t target] new-name",
    "                          Rename a window (renamew)",
    "  select-window -t target Switch to a window (selectw)",
    "  kill-window [-t target] Destroy a window (killw)",
    "",
    "Panes (always the current pane — there is no pane addressing):",
    "",
    "  split-window [-h]       Split the pane: -h side-by-side, default stacked (splitw)",
    "  select-pane -L|-R|-U|-D Move the focus (selectp)",
    "  resize-pane -L|-R|-U|-D [n]",
    "                          Resize by n cells, default 5 (resizep)",
    "  kill-pane               Destroy the current pane (killp)",
    "",
    "Detached sessions keep their windows and panes; reattaching restores the",
    "layout with fresh shells.",
  ].join("\n"),

  printenv: [
    "Usage: printenv [VARIABLE]...",
    "",
    "Print the values of the specified environment VARIABLE(s).",
    "If no VARIABLE is specified, print all environment variables.",
  ].join("\n"),

  export: [
    "Usage: export [NAME=VALUE]...",
    "",
    "Set environment variables in the current shell.",
    "With no arguments, list all exported variables.",
  ].join("\n"),

  unset: [
    "Usage: unset NAME...",
    "",
    "Remove environment variables from the current shell.",
  ].join("\n"),

  alias: [
    "Usage: alias [name[=value] ...]",
    "",
    "Define or display aliases.",
    "With no arguments, list all defined aliases.",
    "",
    "  alias              List all aliases",
    "  alias name         Show definition for name",
    "  alias name='cmd'   Define name as an alias for cmd",
  ].join("\n"),

  unalias: [
    "Usage: unalias [-a] name ...",
    "",
    "Remove alias definitions.",
    "",
    "  unalias name       Remove the alias for name",
    "  unalias -a         Remove all aliases",
  ].join("\n"),
};
